### ISSUE TITLE
Data folder

### ISSUE THREAD

**Issue by AbdulSafdar** [UBC-MDS/522_group_38#9]
I modified the code so that the data folder is created.

It mentions : The data directory should contain a copy of the downloaded data (it should get written there by code). An exception to this can be made if the data set is extremely large (> 100 MB per file). In such cases, please reach out to the instructional team to make an alternative

Should we delete the data folder we currently have? Then rerun the analysis and push the contents of the data directory?

**Comment by Iskanu93** [comment]
Yeah, we can delete the folder.

**Comment by AbdulSafdar** [comment]
Sounds good, I will delete the folder once your edits / proofreading have been committed, then rerun the code and generate the data folder and files and push it. I will make sure it is possible to recreate the analysis from the start and if everything looks good we can probably go ahead with submitting.

**Comment by AbdulSafdar** [comment]
Data folder was generated from code
